server:
  port: 8082
spring:
  application:
    name: GCIIP
  # 限制上传文件以及请求的大小
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    name: defaultDS
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gds?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认600_000(10分钟)
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 事务自动提交
      auto-commit: true
      # 连接最大存活时间，默认1_800_000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认30_000(30秒)
      connection-timeout: 30000
      # 连接测试语句
      connection-test-query: SELECT 1
  # redis配置
  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    database: 1
    password: foxiris@qq.com
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  # 邮箱配置
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    username: supiris@163.com
    password: KCRMQYCKVRVWLHMD
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

mybatis-plus:
  # 开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: cn.iris.gciip.pojo

logging:
  level:
    cn.iris.gciip.mapper: debug

# 文件存储位置
image:
  root: /gciip/image
  plog: /gciip/image/plogs/
  good: /gciip/image/goods/
  errInfo: /gciip/image/errinfos/

# 并发设置参数
concurrent:
  core-pool-size: 5
  max-pool-size: 10
  # 有界队列防止OOM
  queue-size: 20
  # 超出核心数线程的存活时间，单位: 秒
  keep-alive-time: 60
